### ISSUE TITLE
Build failed with error 1

### ISSUE THREAD

**Issue by DoubleClick7** [McArcady/lnp-forge#57]
Running `/bin/lnp-forge build` returns https://pastebin.com/40RSJN4f

**Comment by McArcady** [comment]
Could you attach log file `build.log` ?

**Comment by arkodi** [comment]
I get a similar error. Looks like `patches/kloker/default/100-fix-for-dfhack-47-05.patch` can't be applied because of the changes introduced in [`f5aeb7f`](https://github.com/strainer/cavekeeperdf/commit/f5aeb7fa47859d0d45927c24e755618dccb246b8) in kloker. As a workaround, emptying the patch file worked for me.

**Comment by DoubleClick7** [comment]
@McArcady 
Here are the contents of build.log: https://paste.ee/p/KDhoa

**Comment by McArcady** [comment]
fixed by 6a85f
