### ISSUE TITLE
DFhack version for 47.04 pack.

### ISSUE THREAD

**Issue by clinodev** [McArcady/lnp-forge#7]
Hey there!

If you get me the actual DFhack night version (it probably says in the DFhack window when you load, or on the title screen, or thurin could tell you,) I could put it in the forum thread. lethosor makes a good point here: http://www.bay12forums.com/smf/index.php?topic=175742.msg8105038#msg8105038

![Screenshot (70)](https://user-images.githubusercontent.com/9649547/76698208-7e569900-6676-11ea-895b-03f5e87d77b4.png)

**Comment by McArcady** [comment]
The last pack 47.04-r1 really uses the regular '0.47.04-alpha0' tag of DFHack. This tag corresponds to commit fe2ea1.
The git commit number and 'Build ID' we see on your screenshot does not appear with my build because the lnp-forge script strips away the .git info from the DFHack directory before building. It's an unfortunate feature inherited from 'crosstool-ng', the tool upon which lnp-forge is based.

**Comment by McArcady** [comment]
I'm closing this since the exact dfhack version used in the pack can always be identified using the tag name (here 0.47.04-alpha0), even though lnp-forge unconveniently strips the other information (Git and Build ID).
